name: Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Setup Java and Gradle
        uses: ./.github/actions/setup-java-gradle

      - name: Formatting checks
        run: ./gradlew spotlessCheck

      - name: Build and test
        run: ./gradlew assemble