name: Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java and Gradle
        uses: ./.github/actions/setup-java-gradle

      - name: Formatting checks
        run: ./gradlew spotlessCheck

  unit-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: Run unit tests
        run: ./gradlew test